
exclude = ["migrations/", "build/", "dist/", ".venv/", "__pycache__/", "*.pyc"]
line-length = 120

target-version = "py311"

[lint]
select = ["E", "F", "W", "B", "I", "DJ"]
ignore = ["F403", "E501"]

[format]
quote-style = "double"
indent-style = "space"